version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 10.15
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - dist/**
  discard-paths: yes
