version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - ./*
    - dist/**/*
    - .ebextensions/**/*
  discard-paths: no
